### ISSUE TITLE
BRUH!!!!

### ISSUE THREAD

**Issue by JAYAYAYAYAYAYA** [highfl/-blooket-hacks#5]
You **@highf**l make 10,000 of each blook right?? Well, it does not work!! I sold a Yeti, and guess what?? It got sold and the so called **10,000** of every blooks disappeared! __This Hack does not work! You have to fix this @highfl 
BOOOOO!_

**Comment by SolarFlare1524** [comment]
he needs to fix this and some more but thats all and he's very busy

**Comment by highfl** [comment]
bruh it doesnt give you 10000 of all blooks it only makes it look like you have it. its like spoof blooks but x10,000. since it is a javascript, it gets removed everytime you refresh the page, so when you sold your yeti, it refreshed the page and refreshed to your original blooks. im sorry for your loss but you could have thought more about it before selling a legendary from a random script. @SolarFlare1524 can you tell me the other ones that dont work and i can fix them

**Comment by SolarFlare1524** [comment]
hi and i would love to be moderator because after all, we are the OG's

**Comment by SolarFlare1524** [comment]
and i also thought the guy was saying they didn't show up on the board

**Comment by highfl** [comment]
yeah

**Comment by highfl** [comment]
how do i make you moderator

**Comment by SolarFlare1524** [comment]
idk

**Comment by SolarFlare1524** [comment]
i haven't been on here much for a while

**Comment by SolarFlare1524** [comment]
hi

**Comment by codemaster123puppy** [comment]
@JAYAYAYAYAYAYA it is a spoofer, you would know that if you coded!

**Comment by highfl** [comment]
lol
